### ISSUE TITLE
Support of old standards

### ISSUE THREAD

**Issue by mishako** [rometools/rome2#3]
**Pros**
- Helps developers that need to interact with very old feeds

**Cons**
- Takes development time
- Clutters up the code

Standards I consider old:
- RSS < 2.0 (e.g. RSS 0.9 from 1999)
- Atom < 1.0 (e.g. Atom 0.3 from 2003)

Maybe support reading but not writing of old standards?

We have a slightly related issue in Rome where the RSS 2.0 parser can't accept `<rss version="0.1">` because it doesn't know if there is an RSS 0.1 parser (see [pull request #274](https://github.com/rometools/rome/pull/274) and corresponding [issue #186](https://github.com/rometools/rome/issues/186)).

**Comment by imk** [comment]
I think it's one of Romes advantages supporting multiple feed types (including conversion between formats), so you don't have to care too much about the concrete feed format you're reading. So imho it would be great to keep support for these older feed formats. But on the other side, these parsers and generators must be implemented, tested and kept up to date.

Maybe there can be a balance between dropping support for older formats and supporting every format by implementing feed parsers and generators in some easily pluggable way and having some "core" parsers and generators for up to date formats and some formats like RSS 0.9 are only provided as plugins?Comparable to feed and entry modules today.

**Comment by mishako** [comment]
Looks like the majority is for keeping the support for older formats. At least that's what I see in the [questionnaire ticket](https://github.com/rometools/rome/issues/353) and in the submitted responses.

It doesn't seem to be controversial, so I'm closing the discussion.
