### ISSUE TITLE
Absolute leniency

### ISSUE THREAD

**Issue by mishako** [rometools/rome2#9]
**Pros**
- User is never blocked by partially broken feeds they have no control over

**Cons**
- Developers are used to libraries throwing exceptions if something is wrong
- We're not spreading the culture of following the standards

Things we could be lenient about:
- Incorrect BOM
- Absent XML declaration
- Incorrect declared encoding
- Incorrect or missing XML namespaces
- Unescaped XML entities (`&` instead of proper `&amp`)
- Missing required tags or attributes
- Invalid dates
- Unexpected values

If the feed is so broken we can't fix it, we could throw an exception. Non-fatal errors can be exposed in the API, so that the user can decide if they want to treat them as fatal.

**Comment by PatrickGotthard** [comment]
I think that it's the best to make the behaviour configurable. Rome should be lenient by default but the user should have a chance to activate some sort of "strict mode"

**Comment by imk** [comment]
In the API proposal, there's a `Features.SAVE_ERRORS` mode and an `errors()` method on the parsed feed, I think that's comparable to a *strict mode*, just more flexible. That way, the user can decide if he want's to ignore the feed if there's any error or just for some kind of errors.

**Comment by mishako** [comment]
Closing the ticket: no controversy here as far as I can see. Let's try it out in the prototype and see what works best.
